
classification:
	R -e "rmarkdown::render('Text_classification.Rmd', clean=FALSE, output_file='Text_classification.html')"
	R --vanilla < copy_files.R

word_representation:
	R -e "rmarkdown::render('Word_representations.Rmd', clean=FALSE, output_file='Word_representations.html')"
	R --vanilla < copy_files.R

